---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lemg1635/laravel/
    - export PUBLICPATH=/home/lemg1635/public_html/

    # 1. Update Core Laravel
    - /bin/cp -R * $DEPLOYPATH

    # 2. Update Public Files (Tanpa mengganggu folder storage symlink)
    # Menggunakan rsync lebih aman daripada cp -R untuk folder public
    # agar folder 'storage' yang berupa symlink tidak ikut tertimpa/rusak.
    - /usr/bin/rsync -av --exclude='storage' public/ $PUBLICPATH

    # 3. Jalankan Artisan Command
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan down
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan up